#!/bin/bash

cd tasks/
find \( -path ./all -o -path ./prep  \) -prune -o -path './*/*' -type f -not -name 'prep-*' -exec bash -c 'ln -sf ."$1" all/$(basename "${1%.yml}")' -- {} \;
find \( -path ./all -o -path ./prep  \) -prune -o -path './*/*' -type f -name 'prep-*' -exec bash -c 'ln -sf ."$1" prep/$(basename "${1%.yml}")' -- {} \;
